# Data path. adjust them!
common:
    image_file: "/home/guo/fast_lio_lc_ws/src/livox_camera_calib/result/calib/5.png"
    pcd_file: "/home/guo/fast_lio_lc_ws/src/livox_camera_calib/result/calib/5.pcd"
    result_file: "/home/guo/fast_lio_lc_ws/src/livox_camera_calib/result/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [923.174744, 0.0,      636.617,
                0.0,     923.510071,  370.753418,
                0.0,     0.0,      1.0     ]
    dist_coeffs: [0 , 0, 0, 0, 0]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/guo/fast_lio_lc_ws/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: false # set true if your initial_extrinsic is bad


    # dist_coeffs: [0.1335124, -0.051089125, -0.00085845468, -0.0017382681, -1.0297732965]
    # dist_coeffs: [0 , 0, 0, 0, 0]

        # camera_matrix: [976.722955, 0.0,      631.268620,
        #         0.0,     978.146927,  368.493321,
        #         0.0,     0.0,      1.0     ]

        