# Data path. adjust them!
common:
    image_file: "/home/guo/fast_lio_lc_ws/src/livox_camera_calib/result/calib/"
    pcd_file: "/home/guo/fast_lio_lc_ws/src/livox_camera_calib/result/calib/"
    result_file: "/home/guo/fast_lio_lc_ws/src/livox_camera_calib/result/extrinsic.txt"
    data_num: 3
# Camera Parameters. Adjust them!
camera:
    camera_matrix: [976.722955, 0.0,      631.268620,
                0.0,     978.146927,  368.493321,
                0.0,     0.0,      1.0     ]
    dist_coeffs: [0 , 0, 0, 0, 0]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/ycj/catkin_ws/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
